# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy server code and requirements
COPY . .

# Install specific numpy first to satisfy TensorFlow dependency
RUN pip install --no-cache-dir numpy==1.26.0
# Install TensorFlow
RUN pip install --no-cache-dir tensorflow==2.19.0
# Install remaining dependencies
RUN pip install --no-cache-dir bitstring==4.3.1 ikpy==3.4.2 lxml==5.4.0 matplotlib==3.10.1 mcp==1.6.0 pandas==2.2.3 pydantic==2.11.3 pymodbus==3.9.2 pyserial==3.5 scipy==1.15.2 six==1.17.0 sympy==1.14.0

# Ensure UTF-8 encoding for stdout
ENV PYTHONIOENCODING=utf-8

# Launch the MCP server via stdio
CMD ["python", "main.py"]
